// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gkit"
	"grpcexp/pkg"
)

// Injectors from wire.go:

func InitializeServer(name string) (*gkit.Server, error) {
	grpcLogger := gkit.NewGrpcLogger()
	grpcServer := pkg.NewGrpcServer(grpcLogger)
	runner := pkg.NewRunner(grpcServer)
	closer := pkg.NewCloser()
	migrator := pkg.NewMigrator()
	server := gkit.NewServer(name, runner, closer, migrator)
	return server, nil
}
